platform: "tensorflow_graphdef"
input[
    {
        name:'ImageTensor'
        data: TYPE_UINT8
        dims: [513,513,3]
    }
]
output[
    {
        name:'ResizeBilinear_3'
        data: TYPE_FP32
        dims: [513,513,21]
    }
] 